@Catalog_HostAddress = https://localhost:7039/products

GET {{Catalog_HostAddress}}/
Accept: application/json

###

GET {{Catalog_HostAddress}}/01982ed6-b1c9-7ba2-96c5-be808ecc7804
Accept: application/json

###

POST {{Catalog_HostAddress}}/
Content-Type: application/json
{
    "id": 01982ed6-b1c9-7ba2-96c5-be808ecc7324,
    "name": "New Product",
    "description": "This is a new product",
    "price": 19.99,
    "imageaUrl": "new-product.jpg",
}

###

PUT {{Catalog_HostAddress}}/01982ed6-b1c9-7ba2-96c5-be808ecc7804
Content-Type: application/json
{
    "id": 01982ed6-b1c9-7ba2-96c5-be808ecc7804,
    "name": "Updated Product",
    "description": "This is an updated product",
    "price": 29.99,
    "imageaUrl": "updated-product.jpg",
}

###

DELETE {{Catalog_HostAddress}}/01982ed6-b1c9-7ba2-96c5-be808ecc7804
Accept: application/json

###